pub mod arena;
pub mod audio;
pub mod camera;
pub mod combat;
pub mod element;
pub mod enemies;
pub mod enemy_death;
pub mod experience;
pub mod game;
pub mod inventory;
pub mod loot;
pub mod movement;
pub mod pause;
pub mod player;
pub mod powerup;
pub mod prelude;
pub mod score;
pub mod spell;
pub mod spells;
pub mod states;
pub mod ui;
pub mod visual_test;
pub mod whisper;

pub use arena::plugin as arena_plugin;
pub use audio::plugin as audio_plugin;
pub use camera::plugin as camera_plugin;
pub use combat::plugin as combat_plugin;
pub use enemy_death::plugin as enemy_death_plugin;
pub use experience::plugin as experience_plugin;
pub use game::plugin as game_plugin;
pub use inventory::plugin as inventory_plugin;
pub use loot::plugin as loot_plugin;
pub use movement::plugin as movement_plugin;
pub use pause::plugin as pause_plugin;
pub use powerup::plugin as powerup_plugin;
pub use spell::plugin as spell_plugin;
pub use ui::plugin as ui_plugin;
pub use whisper::plugin as whisper_plugin;
