  pub mod audio;
  pub mod bullets;
  pub mod enemies;
  pub mod enemy_death;
  pub mod experience;
 pub mod game;
 pub mod inventory;
 pub mod laser;
 pub mod loot;
 pub mod pistol;
 pub mod player;
 pub mod powerup;
 pub mod rocket_launcher;
 pub mod score;
 pub mod states;
 pub mod ui;
 pub mod weapon;
 pub mod prelude;

  pub use audio::plugin as audio_plugin;
  pub use enemy_death::plugin as enemy_death_plugin;
  pub use experience::plugin as experience_plugin;
 pub use game::plugin as game_plugin;
 pub use inventory::plugin as inventory_plugin;
 pub use laser::plugin as laser_plugin;
 pub use loot::plugin as loot_plugin;
 pub use powerup::plugin as powerup_plugin;
 pub use rocket_launcher::plugin as rocket_launcher_plugin;
 pub use ui::plugin as ui_plugin;
 pub use weapon::plugin as weapon_plugin;